"""add card_text snapshot to notification_tasks

Revision ID: 66e76f6817a7
Revises: aeee191d5e55
Create Date: 2026-09-13 20:27:45.355592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66e76f6817a7'
down_revision: Union[str, Sequence[str], None] = 'aeee191d5e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_tasks', sa.Column('card_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_tasks', 'card_text')
    # ### end Alembic commands ###
