"""add day_windows table

Revision ID: a254298369b9
Revises: 66e76f6817a7
Create Date: 2026-09-13 23:46:19.583916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a254298369b9'
down_revision: Union[str, Sequence[str], None] = '66e76f6817a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_windows',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'starts_at', name='uq_day_windows_business_starts')
    )
    op.create_index('ix_day_windows_business_date', 'day_windows', ['business_id', 'date'], unique=False)
    op.create_index(op.f('ix_day_windows_business_id'), 'day_windows', ['business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_day_windows_business_id'), table_name='day_windows')
    op.drop_index('ix_day_windows_business_date', table_name='day_windows')
    op.drop_table('day_windows')
    # ### end Alembic commands ###
